language: c

before_install:
  - sudo apt-get -qq update

  # luajit
  - sudo apt-get install luajit
  - sudo ln -s /usr/bin/luajit-2.0.0-beta9 /usr/bin/luajit

  # verilator
  - sudo apt-get install verilator
  - export PKG_CONFIG_PATH=/home/travis/build/jameshegarty/rigel/platform/verilator


  #terra
  - wget https://github.com/zdevito/terra/releases/download/release-2016-02-26/terra-Linux-x86_64-2fa8d0a.zip
  - unzip terra-Linux-x86_64-2fa8d0a.zip
  - sudo ln -s /home/travis/build/jameshegarty/rigel/terra-Linux-x86_64-2fa8d0a/bin/terra /usr/bin/terra

  # this installs correct version of glibc for terra binary
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -y update
  - sudo apt-get -y install libstdc++6-4.7-dev

#  - cd examples
#  - make out/pointwise_wide_handshake.terra.correct.txt
#  - make out/pointwise_wide_handshake.verilator.correct.txt

script:
# early out on errors
  - set -e
  - if [[ $TARGET = "unit" ]]; then cd unittests;  make;  else cd examples;  make -j2 $TARGET; fi
# check that make actually 100% completed, just to be really sure (?)
  - pwd
  - echo out/${TARGET}_done.txt
#  - test -e out/{$TARGET}_done.txt
  - if [[ $TARGET != "unit" ]]; then test -e out/${TARGET}_done.txt || exit; fi

env:
  - TARGET=verilog
  - TARGET=verilator
  - TARGET=terra
  - TARGET=unit
  - TARGET=axiverilog
